### ISSUE TITLE
Reset `pkgrel` to 1 after updating to a new version

### ISSUE THREAD

**Issue by q234rty** [Icelk/aur-updater#1]
The script didn't reset `pkgrel` in [this update](https://aur.archlinux.org/cgit/aur.git/commit/?h=vscodium-bin&id=c3c5f826556385aef2653dde564dd2f86b1914f2).

**Comment by Icelk** [comment]
I’ll fix this is a few hours.
Thanks for bringing this to my attention!

**Comment by Icelk** [comment]
@q234rty 
The issue is now fixed. Next version of the package should have a `pkgrel` of 1.

**Comment by q234rty** [comment]
Thanks for fixing this.
